# -*- coding: utf-8 -*-
"""Feedforward Neural Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkBm70MR_MHOEjeqxWVKIYJc5ZT0iJXv
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from keras.datasets import mnist

# =============================
# a. Load and explore MNIST data
# =============================
(x_train, y_train), (x_test, y_test) = mnist.load_data()

print(f"Shape of X_train {x_train.shape}")
print(f"Shape of y_train {y_train.shape}")
print(f"Shape of x_test  {x_test.shape}")
print(f"Shape of y_test  {y_test.shape}")

print("Image dimensions:", x_train[0].shape)
print("Unique labels in y_train:", np.unique(y_train))

# Display a sample image
plt.imshow(x_train[25], cmap='gray')
plt.title(f"Label: {y_train[25]}")
plt.axis('off')
plt.show()

# =============================
# b. Preprocessing: Normalize input data
# =============================
x_train = x_train / 255.0
x_test = x_test / 255.0

# =============================
# c. Build Feedforward Neural Network
# =============================
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(50, activation='relu', name='L1'),
    keras.layers.Dense(50, activation='relu', name='L2'),
    keras.layers.Dense(10, activation='softmax', name='L3')
])

model.compile(optimizer='sgd',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

# =============================
# d. Train the model
# =============================
history = model.fit(x_train, y_train,
                    batch_size=30,
                    epochs=10,
                    validation_data=(x_test, y_test),
                    shuffle=True)

# =============================
# e. Evaluate the model
# =============================
loss, accuracy = model.evaluate(x_test, y_test)
print(f"\nFinal Test Loss: {loss:.4f}")
print(f"Final Test Accuracy: {accuracy:.4f}")

# =============================
# f. Plot training history
# =============================
plt.figure(figsize=[15, 8])

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy', fontsize=20)
plt.xlabel('Epoch', fontsize=14)
plt.ylabel('Accuracy', fontsize=14)
plt.legend()

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss', fontsize=20)
plt.xlabel('Epoch', fontsize=14)
plt.ylabel('Loss', fontsize=14)
plt.legend()

plt.tight_layout()
plt.show()

# =============================
# g. Predict and visualize a random image
# =============================
predicted_probs = model.predict(x_test)
sample_index = 15
predicted_label = np.argmax(predicted_probs[sample_index])
actual_label = y_test[sample_index]

plt.imshow(x_test[sample_index], cmap='gray')
plt.title(f"Predicted: {predicted_label} | Actual: {actual_label}")
plt.axis('off')
plt.show()

